/**
 * The hand-written core of the book.
 *
 * These are the openings a player actually chooses between, each with the ideas
 * that make it playable rather than just the move order. The full ECO tables
 * (3,810 lines) are imported separately into `eco.generated.ts` and merged in
 * `book.ts`; theory is the part that cannot be imported, so it is written here
 * and inherited downwards by every ECO line beneath it.
 */

import type { Opening } from './types.js';

const line = (moves: string): string[] => moves.split(' ').filter(Boolean);

export const CURATED_OPENINGS: Opening[] = [
  // ---------------------------------------------------------------- 1.e4 ---
  {
    eco: 'B00',
    name: 'King’s Pawn Opening',
    moves: line('e4'),
    character: 'balanced',
    theory: {
      idea: 'Occupies the centre, opens lines for the queen and the light-squared bishop, and asks Black to commit immediately. It leads to the sharpest and most concrete openings in chess — with 1.e4 you must know what you are doing more often than with 1.d4.',
      structures: [],
      whitePlans: ['Follow up with Nf3 and a bishop developed actively', 'Castle early — 1.e4 positions open fast'],
      blackPlans: ['Fight for the centre with 1...e5 or 1...c5', 'Or undermine it with 1...c6, 1...e6 or 1...Nf6'],
      breaks: [],
    },
  },
  { eco: 'C20', name: 'Open Game', moves: line('e4 e5') },
  { eco: 'C40', name: 'King’s Knight Opening', moves: line('e4 e5 Nf3') },
  { eco: 'C44', name: 'King’s Pawn Game', moves: line('e4 e5 Nf3 Nc6') },
  {
    eco: 'C60',
    name: 'Ruy Lopez (Spanish)',
    moves: line('e4 e5 Nf3 Nc6 Bb5'),
    character: 'positional',
    minRating: 1400,
    aliases: ['Spanish Game'],
    theory: {
      idea: 'White develops with a threat against the defender of e5 and prepares to build a big centre with c3 and d4 while Black is still untangling. The Spanish is the deepest positional opening in chess: both sides manoeuvre for twenty moves before anything opens, and understanding the structure matters far more than memorising lines.',
      structures: ['spanish-closed'],
      whitePlans: [
        'Build the centre with c3 and d4 and maintain the tension as long as possible.',
        'The Spanish knight route Nb1-d2-f1-g3 or -e3, swinging toward the kingside.',
        'a4 to create a second front against Black’s queenside pawns.',
        'Trade on c6 at a moment when the doubled pawns actually hurt.',
      ],
      blackPlans: [
        'Play ...a6 and ...b5 to gain queenside space and kick the bishop.',
        'Achieve ...d6-d5 in a single move — the central goal of the whole defence.',
        'The Chigorin (...Na5, ...c5) or Breyer (...Nb8-d7) regroupings.',
        'The Marshall Attack: sacrifice a pawn with ...d5 for a lasting kingside initiative.',
      ],
      breaks: [
        { move: 'd5', side: 'black', note: 'The equalising break. In one move it solves everything; in two it usually solves nothing.' },
        { move: 'c5', side: 'black', note: 'Chigorin-style pressure against d4.' },
        { move: 'd4', side: 'white', note: 'The central advance the opening is built toward; timing decides whether it gains or releases the advantage.' },
        { move: 'a4', side: 'white', note: 'Opens a second front against b5, often at the moment Black commits to the centre.' },
      ],
      keySquares: [
        { square: 'd5', note: 'Black equalises by getting a pawn here; White’s whole setup is designed to stop it.' },
        { square: 'f5', note: 'The Spanish knight’s destination via d2-f1-g3.' },
      ],
      routes: ['Nb1-d2-f1-g3', 'Nb8-d7-f8-g6 (Breyer)'],
      traps: ['The Noah’s Ark trap: grabbing the e5 pawn too early can cost the bishop after ...c5, ...c4 and ...b5.'],
      modelGames: ['Karpov – Unzicker, Nice 1974', 'Kasparov – Karpov, World Championship 1990'],
    },
  },
  { eco: 'C65', name: 'Ruy Lopez: Berlin Defence', moves: line('e4 e5 Nf3 Nc6 Bb5 Nf6'), character: 'positional' },
  { eco: 'C68', name: 'Ruy Lopez: Exchange Variation', moves: line('e4 e5 Nf3 Nc6 Bb5 a6 Bxc6'), character: 'positional' },
  {
    eco: 'C84',
    name: 'Ruy Lopez: Closed',
    moves: line('e4 e5 Nf3 Nc6 Bb5 a6 Ba4 Nf6 O-O Be7 Re1 b5 Bb3 d6 c3 O-O'),
    character: 'positional',
    minRating: 1600,
    theory: {
      idea: 'The main line of the main line. The centre locks into the classic c3/d4/e4 versus d6/e5 formation and both sides regroup behind the pawns for many moves. Nothing is decided by tactics here — it is decided by which pieces reach which squares.',
      structures: ['spanish-closed'],
      whitePlans: [
        'Nbd2-f1-g3 and then Nf5 or Bg5 with kingside pressure.',
        'Keep the central tension; releasing it with d5 or dxe5 usually helps Black.',
        'a4 to open a second front on the queenside.',
      ],
      blackPlans: [
        'Chigorin: ...Na5, ...c5, ...Qc7 hitting d4.',
        'Breyer: ...Nb8-d7 rerouting the knight to a better home.',
        'Zaitsev: ...Bb7 and ...Re8 pressing e4 directly.',
      ],
      breaks: [
        { move: 'd5', side: 'black', note: 'Full equality if achieved in one move with pieces ready.' },
        { move: 'c5', side: 'black', note: 'The Chigorin plan; gains space and pressures d4.' },
        { move: 'd5', side: 'white', note: 'Locks the centre and starts a wing race — a decision, not a default.' },
      ],
      routes: ['Nb1-d2-f1-g3', 'Nc6-a5 and ...c5 (Chigorin)', 'Nc6-b8-d7 (Breyer)'],
      modelGames: ['Karpov – Unzicker, Nice 1974'],
    },
  },
  {
    eco: 'C50',
    name: 'Italian Game',
    moves: line('e4 e5 Nf3 Nc6 Bc4'),
    character: 'balanced',
    minRating: 800,
    theory: {
      idea: 'The most natural opening in chess: develop a piece, point it at f7, castle. Modern practice plays it slowly with d3 and c3, building the centre with a later d4 — the same structures as the Spanish, reached with far less theory. This is the best first e4 opening for almost every improving player.',
      structures: ['spanish-closed'],
      whitePlans: [
        'The slow build-up c3, d3, Nbd2, Bb3, Re1 and then d4 at the right moment.',
        'Nbd2-f1-g3 exactly as in the Spanish.',
        'The Evans Gambit (b4) if you want the sharp version.',
      ],
      blackPlans: [
        'Mirror the setup with ...d6, ...Nf6, ...a6, ...Ba7 and ...0-0.',
        'The Two Knights (...Nf6) inviting immediate complications.',
        'Break with ...d5 once White has committed to d3.',
      ],
      breaks: [
        { move: 'd4', side: 'white', note: 'The central break the whole slow setup prepares. Play it when Black cannot answer with a comfortable ...exd4 and ...d5.' },
        { move: 'd5', side: 'black', note: 'The freeing break, usually after ...Re8 and ...Bf8.' },
        { move: 'a4', side: 'white', note: 'Standard on the queenside once Black plays ...a6 and ...b5.' },
      ],
      keySquares: [{ square: 'f7', note: 'The bishop on c4 points here — the reason early tactics exist in this opening at all.' }],
      traps: [
        'Fried Liver: after 3...Nf6 4.Ng5 d5 5.exd5 Nxd5?! 6.Nxf7 White gets a dangerous attack. Black should prefer 5...Na5.',
        'Never grab the b2 pawn with the queen in the Italian without calculating Rb1 and the tempo loss.',
      ],
      modelGames: ['Anand – Carlsen, Grenke 2019'],
    },
  },
  { eco: 'C53', name: 'Italian Game: Giuoco Piano', moves: line('e4 e5 Nf3 Nc6 Bc4 Bc5 c3') },
  { eco: 'C55', name: 'Italian Game: Two Knights Defence', moves: line('e4 e5 Nf3 Nc6 Bc4 Nf6'), character: 'sharp' },
  { eco: 'C51', name: 'Evans Gambit', moves: line('e4 e5 Nf3 Nc6 Bc4 Bc5 b4'), character: 'gambit' },
  {
    eco: 'C42',
    name: 'Petrov Defence (Russian Game)',
    moves: line('e4 e5 Nf3 Nf6'),
    character: 'positional',
    forSide: 'black',
    theory: {
      idea: 'Instead of defending e5, Black counter-attacks e4. It leads to symmetrical, drawish, extremely solid positions — the classic choice for a player who wants to neutralise 1.e4 rather than fight it.',
      structures: [],
      whitePlans: ['Play d4 and fight for a small space advantage', 'The sharp 3.Nxe5 lines where accuracy matters early'],
      blackPlans: ['Trade pieces and head for equality', 'Complete development quickly; the structures are symmetrical and nothing is weak'],
      breaks: [{ move: 'd5', side: 'black', note: 'Central equaliser after the knights are traded.' }],
      traps: ['3.Nxe5 Nxe4?? loses material to 4.Qe2 — Black must play 3...d6 first.'],
    },
  },
  {
    eco: 'C45',
    name: 'Scotch Game',
    moves: line('e4 e5 Nf3 Nc6 d4'),
    character: 'balanced',
    minRating: 1000,
    theory: {
      idea: 'White opens the centre immediately rather than building up. It avoids the enormous body of Spanish theory and gives clear, straightforward play — good for a player who wants an open game without memorising twenty moves.',
      structures: [],
      whitePlans: ['Develop with Nxd4, Nc3, Be3, Qd2 and castle', 'Play c4 to grip d5', 'Push e5 to gain space when Black is slow'],
      blackPlans: ['Hit the d4 knight with ...Bc5 or ...Nf6', 'Trade into an equal structure and finish development', 'The Mieses variation ...Nf6 5.Nxc6 bxc6 6.e5 with a sharp fight over the doubled pawns'],
      breaks: [
        { move: 'c4', side: 'white', note: 'Clamps d5 and prepares a bind.' },
        { move: 'd5', side: 'black', note: 'The standard central freeing move once White plays e5.' },
        { move: 'f6', side: 'black', note: 'Undermines a white pawn on e5.' },
      ],
    },
  },
  { eco: 'C41', name: 'Philidor Defence', moves: line('e4 e5 Nf3 d6'), character: 'positional' },
  { eco: 'C25', name: 'Vienna Game', moves: line('e4 e5 Nc3') },
  {
    eco: 'C30',
    name: 'King’s Gambit',
    moves: line('e4 e5 f4'),
    character: 'gambit',
    theory: {
      idea: 'White gives a pawn to deflect the e5 pawn and seize the centre with d4, plus a half-open f-file for the attack. Objectively risky, practically dangerous, and an outstanding way to learn attacking chess.',
      structures: [],
      whitePlans: ['Take the centre with d4 and develop with Nf3 and Bc4', 'Attack down the f-file after castling short', 'Regain the gambit pawn only when it costs nothing'],
      blackPlans: ['Accept and hold the pawn with ...g5 — critical but committal', 'Decline with 2...Bc5, taking aim at the weakened a7-g1 diagonal', 'Counter in the centre with 2...d5, the Falkbeer'],
      breaks: [
        { move: 'd4', side: 'white', note: 'The move that justifies the pawn sacrifice.' },
        { move: 'd5', side: 'black', note: 'The standard central counter-strike against any gambit.' },
      ],
      traps: ['After 3.Nf3 g5 4.h4 g4 5.Ne5 (Kieseritzky) the position is razor-sharp — do not enter it unprepared from either side.'],
    },
  },

  // -------------------------------------------------------------- Sicilian ---
  {
    eco: 'B20',
    name: 'Sicilian Defence',
    moves: line('e4 c5'),
    character: 'sharp',
    forSide: 'black',
    minRating: 1200,
    theory: {
      idea: 'Black meets a central pawn with a flank pawn, trading a c-pawn for White’s d-pawn. That leaves Black with a central pawn majority and a half-open c-file at the cost of development time and king safety. It is the most-played and highest-scoring defence to 1.e4, and it is unbalanced from move one — nobody drifts to a draw in a Sicilian.',
      structures: ['boleslavsky', 'scheveningen', 'maroczy', 'hedgehog'],
      whitePlans: [
        'Open Sicilian: 2.Nf3 and 3.d4 for a lead in development and attacking chances.',
        'Attack the king, usually with f4-f5, g4-g5 or a sacrifice on d5 or e6.',
        'Fight for d5 — in almost every Sicilian, that square is the battleground.',
        'Anti-Sicilians (Alapin, Rossolimo, Closed) to avoid theory and play a positional game.',
      ],
      blackPlans: [
        'Counterattack on the queenside down the half-open c-file with ...Rc8, ...Qc7, ...b5-b4.',
        'Achieve ...d5 in one move; that is usually full equality or better.',
        'Trade off White’s attacking pieces, especially the dark-squared bishop.',
        'Accept a worse structure for active pieces — that is the deal the Sicilian offers.',
      ],
      breaks: [
        { move: 'd5', side: 'black', note: 'The central break that ends White’s initiative, in nearly every Sicilian line.' },
        { move: 'b5', side: 'black', note: 'Gains space, drives the c3 knight off the defence of e4 and d5.' },
        { move: 'f5', side: 'white', note: 'The standard attacking break against a pawn on e6.' },
        { move: 'g4', side: 'white', note: 'The pawn storm; usually played with the king on the queenside or still in the centre.' },
      ],
      keySquares: [
        { square: 'd5', note: 'White wants a piece there permanently; Black wants a pawn there once.' },
        { square: 'c4', note: 'Black’s knight outpost via ...Na5-c4 or ...Ne5-c4.' },
      ],
      modelGames: ['Fischer – Larsen, Portoroz 1958', 'Kasparov – Topalov, Wijk aan Zee 1999'],
    },
  },
  { eco: 'B50', name: 'Sicilian Defence: Modern Variation', moves: line('e4 c5 Nf3 d6') },
  {
    eco: 'B90',
    name: 'Sicilian Defence: Najdorf Variation',
    moves: line('e4 c5 Nf3 d6 d4 cxd4 Nxd4 Nf6 Nc3 a6'),
    character: 'sharp',
    forSide: 'black',
    minRating: 1800,
    aliases: ['Najdorf'],
    theory: {
      idea: 'The most analysed opening in chess. 5...a6 is a small, flexible move: it takes b5 from White’s pieces and prepares ...e5 or ...e6 depending on what White does. Black keeps every option open and dares White to prove the initiative is worth something. It demands real theoretical work — this is not an opening to improvise.',
      structures: ['boleslavsky', 'scheveningen'],
      whitePlans: [
        'English Attack: Be3, f3, Qd2, 0-0-0 and g4-g5 — the main try, a direct race.',
        '6.Bg5 pinning the knight and playing for the d5 square and f4-f5.',
        '6.Bc4 hitting f7 and e6 before Black is organised.',
        'Positional 6.Be2 and 0-0, playing against the d5 hole slowly.',
      ],
      blackPlans: [
        '...e5 hitting the knight, taking d4, accepting the d5 hole (the Boleslavsky bargain).',
        '...e6 keeping the small centre flexible and transposing to Scheveningen structures.',
        'Queenside expansion with ...b5, ...Bb7, ...Nbd7 and ...Rc8.',
        'Meet a kingside storm with a faster queenside one; count the moves honestly.',
      ],
      breaks: [
        {
          move: 'b5',
          side: 'black',
          note: 'The standard counterplay: drives the knight from c3, opens the b-file, supports ...b4 and ...d5.',
          prerequisites: ['...a6 played', 'Ready to meet a4 with ...b4 or ...Nbd7-c5'],
        },
        { move: 'd5', side: 'black', note: 'The liberating break. Achieving it in one move usually means Black is at least equal.' },
        { move: 'g5', side: 'white', note: 'The English Attack storm; kicks the f6 knight off the defence of d5.' },
        { move: 'f5', side: 'white', note: 'Hits e6 and opens the f-file when Black has chosen the small centre.' },
      ],
      keySquares: [
        { square: 'd5', note: 'The permanent hole after ...e5. Black must be able to cover it with ...Be6, ...Nbd7 and ...b5-b4.' },
        { square: 'b5', note: 'Denied to White by ...a6; Black wants a pawn here instead.' },
      ],
      traps: ['In the 6.Bg5 Poisoned Pawn (...Qb6 taking on b2) both sides are following analysis 25 moves deep. Do not enter it from memory alone.'],
      modelGames: ['Kasparov – Topalov, Wijk aan Zee 1999', 'Fischer – Spassky, Reykjavik 1972 (g.13)'],
    },
  },
  {
    eco: 'B80',
    name: 'Sicilian Defence: Scheveningen Variation',
    moves: line('e4 c5 Nf3 e6 d4 cxd4 Nxd4 Nf6 Nc3 d6'),
    character: 'sharp',
    forSide: 'black',
    minRating: 1700,
    theory: {
      idea: 'The small centre: pawns on d6 and e6 concede space but leave no weaknesses at all. Black’s pieces have a modest but flexible home and both ...d5 and ...e5 stay available. White must attack quickly or the structure simply holds.',
      structures: ['scheveningen'],
      whitePlans: ['Keres Attack with g4 before Black castles', 'English Attack: Be3, f3, Qd2, 0-0-0, g4', 'f4-f5 hitting e6'],
      blackPlans: ['Standard setup ...Be7, ...0-0, ...a6, ...Qc7, ...Nc6, ...Bd7', 'The ...Nc6-a5-c4 manoeuvre trading White’s attacker', 'Break with ...d5 or ...b5 at the right moment'],
      breaks: [
        { move: 'd5', side: 'black', note: 'The main equalising break.' },
        { move: 'b5', side: 'black', note: 'Queenside counterplay, hitting the knight that guards d5 and e4.' },
        { move: 'g4', side: 'white', note: 'The Keres Attack — starts before development is complete, which is the whole point.' },
        { move: 'f5', side: 'white', note: 'Pries open e6 and the f-file.' },
      ],
    },
  },
  {
    eco: 'B70',
    name: 'Sicilian Defence: Dragon Variation',
    moves: line('e4 c5 Nf3 d6 d4 cxd4 Nxd4 Nf6 Nc3 g6'),
    character: 'sharp',
    forSide: 'black',
    minRating: 1600,
    theory: {
      idea: 'Black fianchettoes on g7 and points the bishop at the queenside along the long diagonal. In the Yugoslav Attack both sides castle on opposite wings and simply race: White with h4-h5 and Bh6, Black down the c-file with ...Rxc3. Move-for-move counting matters more than evaluation.',
      structures: ['boleslavsky'],
      whitePlans: [
        'Yugoslav Attack: Be3, Qd2, f3, 0-0-0, then h4-h5 and Bh6 to trade the Dragon bishop.',
        'Trade the g7 bishop at almost any cost — it is Black’s best piece and best defender.',
        'Open the h-file with hxg6 and mate.',
      ],
      blackPlans: [
        'The exchange sacrifice ...Rxc3 wrecking White’s queenside pawn cover — a standard idea, not a desperate one.',
        'Play ...Rc8, ...Ne5-c4 and ...Qa5 as fast as possible.',
        'Keep the g7 bishop alive; meet Bh6 with ...Bh8 when the tempo allows.',
      ],
      breaks: [
        { move: 'h5', side: 'white', note: 'Opens the h-file; the core of the Yugoslav Attack.' },
        { move: 'b5', side: 'black', note: 'Standard queenside expansion feeding the attack on c3 and the long diagonal.' },
        { move: 'd5', side: 'black', note: 'Central break that frees the g7 bishop with tempo.' },
      ],
      keySquares: [{ square: 'c3', note: 'The target of Black’s entire attack, usually removed by ...Rxc3.' }],
    },
  },
  { eco: 'B33', name: 'Sicilian Defence: Sveshnikov Variation', moves: line('e4 c5 Nf3 Nc6 d4 cxd4 Nxd4 Nf6 Nc3 e5'), character: 'sharp', minRating: 1800 },
  {
    eco: 'B36',
    name: 'Sicilian Defence: Accelerated Dragon, Maróczy Bind',
    moves: line('e4 c5 Nf3 Nc6 d4 cxd4 Nxd4 g6 c4'),
    character: 'positional',
    theory: {
      idea: 'White answers the Accelerated Dragon by clamping the position with pawns on c4 and e4. Black gets a solid but cramped game with no weaknesses and exactly two freeing breaks. It is the model position for learning how to play with and against a space advantage.',
      structures: ['maroczy', 'hedgehog'],
      whitePlans: ['Restrain ...b5 and ...d5 with Be2, Be3, Qd2, Rc1 and f3', 'Trade the dark-squared bishops to expose d6', 'Advance b4-b5 and c5 slowly'],
      blackPlans: ['Trade minor pieces — every exchange makes the space matter less', 'Prepare ...b5 with ...a6 and ...Rb8', 'The ...Nxd4 and ...Bg7xc3 idea to weaken the queenside'],
      breaks: [
        { move: 'b5', side: 'black', note: 'The main freeing break; needs preparation and usually a pawn sacrifice.' },
        { move: 'd5', side: 'black', note: 'Instant equality when it works — which is rarely, and only after trades.' },
        { move: 'b4', side: 'white', note: 'Queenside expansion to fix Black’s pawns and stop ...b5 permanently.' },
      ],
    },
  },
  {
    eco: 'B22',
    name: 'Sicilian Defence: Alapin Variation',
    moves: line('e4 c5 c3'),
    character: 'positional',
    minRating: 1000,
    theory: {
      idea: 'White prepares d4 with a pawn instead of a piece, aiming for a big centre. It sidesteps every Sicilian main line at the cost of ambition — an excellent practical choice for a player who does not want to memorise the Najdorf and the Dragon and the Sveshnikov.',
      structures: ['iqp'],
      whitePlans: ['Build the centre with d4 and recapture with the c-pawn or piece', 'Accept an IQP and play for the attack with Bd3, Re1 and Ne5', 'Gain space with d5 when Black plays ...e6 and ...Nf6'],
      blackPlans: ['2...Nf6 hitting e4 immediately, then ...d5 or ...d6', '2...d5 3.exd5 Qxd5 with quick development', 'Blockade the isolated d-pawn on d5 and trade pieces'],
      breaks: [
        { move: 'd4', side: 'white', note: 'The whole point of 2.c3; play it before Black finishes development.' },
        { move: 'd5', side: 'black', note: 'The standard central answer to any slow White setup.' },
        { move: 'e5', side: 'black', note: 'Blunts a white IQP and takes the d4 square.' },
      ],
    },
  },
  { eco: 'B30', name: 'Sicilian Defence: Rossolimo Variation', moves: line('e4 c5 Nf3 Nc6 Bb5'), character: 'positional' },
  { eco: 'B51', name: 'Sicilian Defence: Moscow Variation', moves: line('e4 c5 Nf3 d6 Bb5+'), character: 'positional' },
  { eco: 'B23', name: 'Sicilian Defence: Closed Variation', moves: line('e4 c5 Nc3'), character: 'system' },
  { eco: 'B40', name: 'Sicilian Defence: Kan Variation', moves: line('e4 c5 Nf3 e6 d4 cxd4 Nxd4 a6'), character: 'balanced' },
  { eco: 'B47', name: 'Sicilian Defence: Taimanov Variation', moves: line('e4 c5 Nf3 e6 d4 cxd4 Nxd4 Nc6'), character: 'balanced' },

  // ---------------------------------------------------------------- French ---
  {
    eco: 'C00',
    name: 'French Defence',
    moves: line('e4 e6'),
    character: 'positional',
    forSide: 'black',
    minRating: 1000,
    theory: {
      idea: 'Black prepares ...d5 to challenge the centre immediately. The structure is famously solid and famously one-sided: Black gets a queenside pawn majority and clear plans, White gets space and kingside attacking chances, and Black’s light-squared bishop has to be solved rather than developed.',
      structures: ['french-chain'],
      whitePlans: ['Advance with e5, gaining space and attacking the kingside', 'Trade on d5 for a symmetrical, quieter game', 'Nd2 (Tarrasch) or Nc3 (Classical/Winawer) supporting e4 and fighting for the centre'],
      blackPlans: ['Attack the base of the chain with ...c5 and ...Qb6', 'Solve the light-squared bishop with ...b6/...Ba6 or ...Bd7-b5', 'Play ...f6 to hit the head of the chain when the king is safe'],
      breaks: [
        { move: 'c5', side: 'black', note: 'The primary break in every French structure — against d4, the base of the chain.' },
        { move: 'f6', side: 'black', note: 'The secondary break; frees the position but opens lines toward Black’s own king.' },
        { move: 'f4', side: 'white', note: 'Supports e5 and prepares f5, the attacking break.' },
      ],
      keySquares: [
        { square: 'd4', note: 'The base of White’s chain and Black’s main target.' },
        { square: 'e5', note: 'White’s space-gaining wedge; the whole opening is a fight over whether it survives.' },
      ],
      modelGames: ['Nimzowitsch – Salwe, Karlsbad 1911'],
    },
  },
  {
    eco: 'C02',
    name: 'French Defence: Advance Variation',
    moves: line('e4 e6 d4 d5 e5'),
    character: 'positional',
    theory: {
      idea: 'White locks the centre at once and stakes everything on the kingside. Play is completely schematic: Black hammers d4, White defends it and plays for f4-f5. It is the clearest illustration of pawn-chain theory in the whole opening repertoire.',
      structures: ['french-chain'],
      whitePlans: ['Defend d4 with c3, Nf3, Be3 and sometimes Qd2 and Ne2', 'Attack with f4-f5, Qg4, Bd3 and Ng5', 'Meet ...Qb6 pressure on b2 without weakening the chain'],
      blackPlans: ['...c5, ...Nc6, ...Qb6 and ...Nge7-f5 piling on d4', 'Trade the bad bishop with ...Bd7-b5 or ...b6 and ...Ba6', 'Win d4 or force a favourable release of the tension'],
      breaks: [
        { move: 'c5', side: 'black', note: 'Immediate and near-automatic; the point of the whole setup.' },
        { move: 'f6', side: 'black', note: 'The second break, once the king is safe and e6 is defensible.' },
        { move: 'f5', side: 'white', note: 'Opens the kingside where White has the extra space.' },
      ],
    },
  },
  { eco: 'C03', name: 'French Defence: Tarrasch Variation', moves: line('e4 e6 d4 d5 Nd2'), character: 'positional' },
  { eco: 'C11', name: 'French Defence: Classical Variation', moves: line('e4 e6 d4 d5 Nc3 Nf6') },
  {
    eco: 'C15',
    name: 'French Defence: Winawer Variation',
    moves: line('e4 e6 d4 d5 Nc3 Bb4'),
    character: 'sharp',
    minRating: 1600,
    theory: {
      idea: 'Black pins the knight and usually trades on c3, handing White the bishop pair and doubled pawns. White gets a big centre and attacking chances; Black gets a permanent structural target on c3 and play against the doubled pawns. Deeply unbalanced and one of the sharpest positional openings there is.',
      structures: ['french-chain'],
      whitePlans: ['Play Qg4 hitting g7 before Black consolidates', 'Use the bishop pair and the space in an open position', 'Attack the kingside with h4-h5 and Rh3-g3'],
      blackPlans: ['Attack the doubled c-pawns with ...c5, ...Qa5 and ...Nc6', 'Avoid ...g6 weaknesses when meeting Qg4 — ...Qc7 or ...Kf8 are the alternatives', 'Reach an endgame where c3 and c2 are simply weak'],
      breaks: [
        { move: 'c5', side: 'black', note: 'Hits d4 and opens lines against the doubled pawns at the same time.' },
        { move: 'f6', side: 'black', note: 'Standard second break; timing is critical with the king often still on e8.' },
        { move: 'f4', side: 'white', note: 'Reinforces e5 and prepares the kingside attack.' },
      ],
    },
  },
  { eco: 'C01', name: 'French Defence: Exchange Variation', moves: line('e4 e6 d4 d5 exd5'), character: 'balanced' },

  // ------------------------------------------------------------ Caro-Kann ---
  {
    eco: 'B10',
    name: 'Caro-Kann Defence',
    moves: line('e4 c6'),
    character: 'positional',
    forSide: 'black',
    minRating: 1200,
    theory: {
      idea: 'Black prepares ...d5 with the c-pawn instead of the e-pawn, which keeps the light-squared bishop free — the one problem the French never solves. The price is a tempo and a slightly passive game. Extremely solid, endgame-friendly, and a good defence for a player who likes structure over chaos.',
      structures: ['carlsbad', 'iqp'],
      whitePlans: ['Advance with 3.e5 gaining space and attacking the b1-h7 diagonal', 'Exchange and play the Panov with c4, heading for an IQP attack', 'Classical 3.Nc3 dxe4 4.Nxe4 fighting for a small edge with better development'],
      blackPlans: ['Develop the light-squared bishop outside the pawn chain with ...Bf5 or ...Bg4', 'Break with ...c5 to hit d4', 'Head for a good structure and an endgame where the extra pawn island tells'],
      breaks: [
        { move: 'c5', side: 'black', note: 'The main freeing break in almost every Caro-Kann structure.' },
        { move: 'e5', side: 'black', note: 'The alternative central break, usually after ...Nd7 and ...Ngf6.' },
        { move: 'f4', side: 'white', note: 'Supports e5 and prepares a kingside advance in the Advance Variation.' },
      ],
      modelGames: ['Capablanca – Nimzowitsch, New York 1927'],
    },
  },
  { eco: 'B12', name: 'Caro-Kann Defence: Advance Variation', moves: line('e4 c6 d4 d5 e5'), character: 'positional' },
  {
    eco: 'B13',
    name: 'Caro-Kann Defence: Exchange Variation',
    moves: line('e4 c6 d4 d5 exd5 cxd5'),
    character: 'positional',
    theory: {
      idea: 'A direct route to the Carlsbad structure with colours effectively reversed from the Exchange QGD. White plays the minority attack with b4-b5; Black plays in the centre and on the kingside. Quiet on the surface, deeply plan-driven underneath.',
      structures: ['carlsbad'],
      whitePlans: ['The minority attack: a4, b4, b5 creating a weakness on c6', 'Bd3, c3, Qc2 with kingside pressure', 'Rb1 and Rc1 to support the queenside advance'],
      blackPlans: ['Meet b5 with ...a6 or ...c5', 'Central and kingside play with ...Ne4 and ...f5', 'Trade the light-squared bishops with ...Bf5 or ...Bg4'],
      breaks: [
        { move: 'b5', side: 'white', note: 'The minority attack; leaves Black with a backward c6 pawn.' },
        { move: 'c5', side: 'black', note: 'Freeing break that accepts an isolani for activity.' },
        { move: 'f5', side: 'black', note: 'Uses the kingside majority.' },
      ],
    },
  },
  {
    eco: 'B14',
    name: 'Caro-Kann Defence: Panov Attack',
    moves: line('e4 c6 d4 d5 exd5 cxd5 c4'),
    character: 'sharp',
    theory: {
      idea: 'White converts the Caro-Kann into an isolated-queen’s-pawn position by force. The resulting IQP structures are the standard textbook material: White attacks with the pieces, Black blockades on d5 and heads for the endgame.',
      structures: ['iqp'],
      whitePlans: ['Attack with Bd3, Qd3/Qc2, Ne5, Rad1 and Re1', 'Occupy e5', 'Time the d4-d5 break to liquidate the weakness at a good moment'],
      blackPlans: ['Blockade d5 with a knight', 'Trade minor pieces, especially White’s attacking bishop', 'Reach an endgame where the isolated pawn is just weak'],
      breaks: [
        { move: 'd5', side: 'white', note: 'The freeing break; needs more attackers than blockaders.' },
        { move: 'e5', side: 'black', note: 'Counter-break when White’s attack has stalled.' },
      ],
    },
  },
  { eco: 'B18', name: 'Caro-Kann Defence: Classical Variation', moves: line('e4 c6 d4 d5 Nc3 dxe4 Nxe4 Bf5'), character: 'positional' },

  // ------------------------------------------------- other answers to 1.e4 ---
  { eco: 'B01', name: 'Scandinavian Defence', moves: line('e4 d5'), character: 'balanced', forSide: 'black' },
  { eco: 'B02', name: 'Alekhine Defence', moves: line('e4 Nf6'), character: 'sharp', forSide: 'black' },
  { eco: 'B06', name: 'Modern Defence', moves: line('e4 g6'), character: 'system', forSide: 'black' },
  { eco: 'B07', name: 'Pirc Defence', moves: line('e4 d6 d4 Nf6 Nc3'), character: 'system', forSide: 'black' },

  // ---------------------------------------------------------------- 1.d4 ---
  {
    eco: 'A40',
    name: 'Queen’s Pawn Opening',
    moves: line('d4'),
    character: 'positional',
    theory: {
      idea: 'Takes the centre with a pawn that is already defended, which is why 1.d4 openings are slower and more strategic than 1.e4 ones. Positions stay closed longer, plans matter more than calculation, and the theory burden is lighter.',
      structures: [],
      whitePlans: ['Follow with c4 to fight for d5 and open the queenside', 'Or play a system (London, Colle) with a fixed setup against almost anything'],
      blackPlans: ['Contest the centre with ...d5 or ...Nf6 and ...e6/...g6', 'Choose between symmetry (...d5) and asymmetry (Indian defences)'],
      breaks: [],
    },
  },
  {
    eco: 'D06',
    name: 'Queen’s Gambit',
    moves: line('d4 d5 c4'),
    character: 'positional',
    minRating: 1200,
    theory: {
      idea: 'Not a real gambit: White offers the c-pawn to deflect Black’s d-pawn and take over the centre, and can always recover it. The whole opening revolves around whether Black can achieve ...c5 or ...e5 without wrecking the structure.',
      structures: ['carlsbad', 'iqp', 'semi-slav-triangle'],
      whitePlans: ['Recapture on c4 with the bishop and build with e3, Nf3 and 0-0', 'Play for e4, the central advance that gives a real space advantage', 'The minority attack after an exchange on d5'],
      blackPlans: ['Defend the centre with ...e6 (QGD) or ...c6 (Slav)', 'Take the pawn and give the centre back with ...dxc4 and ...c5 (QGA)', 'Achieve ...c5 or ...e5 to free the position'],
      breaks: [
        { move: 'c5', side: 'black', note: 'The main freeing break in most Queen’s Gambit structures.' },
        { move: 'e5', side: 'black', note: 'The other release, usually needing ...Nbd7 and ...Re8 first.' },
        { move: 'e4', side: 'white', note: 'The central break White builds toward all opening long.' },
        { move: 'b5', side: 'white', note: 'The minority attack in Carlsbad structures.' },
      ],
    },
  },
  {
    eco: 'D30',
    name: 'Queen’s Gambit Declined',
    moves: line('d4 d5 c4 e6'),
    character: 'positional',
    forSide: 'black',
    minRating: 1200,
    theory: {
      idea: 'The most classical, most reliable answer to 1.d4. Black builds a solid wall and accepts a slightly passive light-squared bishop in exchange for a structure with no weaknesses. The entire middlegame is about freeing that bishop and getting in ...c5 or ...e5.',
      structures: ['carlsbad', 'hanging-pawns', 'iqp'],
      whitePlans: ['Exchange on d5 and play the minority attack', 'Build with Bg5, e3, Nf3, Bd3 and play for e4', 'Pressure the pinned f6 knight and the d5 pawn'],
      blackPlans: ['Free the game with ...c5 or ...dxc4 followed by ...c5', 'The Tartakower plan ...b6 and ...Bb7 solving the bad bishop', 'Trade pieces with ...Ne4 to relieve the cramp'],
      breaks: [
        { move: 'c5', side: 'black', note: 'The main freeing break; often worth an isolated pawn.' },
        { move: 'e5', side: 'black', note: 'The alternative, usually after ...Nbd7 and ...Re8.' },
        { move: 'b5', side: 'white', note: 'The minority attack once the structure becomes Carlsbad.' },
        { move: 'e4', side: 'white', note: 'The central break; prepared with f3 or Bd3 and Qc2.' },
      ],
      modelGames: ['Capablanca – Alekhine, Buenos Aires 1927'],
    },
  },
  {
    eco: 'D35',
    name: 'Queen’s Gambit Declined: Exchange Variation',
    moves: line('d4 d5 c4 e6 Nc3 Nf6 cxd5 exd5'),
    character: 'positional',
    theory: {
      idea: 'The purest Carlsbad position and the classic minority-attack laboratory. White plays b4-b5 to manufacture a weakness on c6; Black counters in the centre or on the kingside. Slow, schematic, and enormously instructive.',
      structures: ['carlsbad'],
      whitePlans: ['Minority attack with Rb1, a3, b4, b5', 'Central alternative with f3 and e4', 'Kingside attack with Ne5, f3, g4 if Black plays on the queenside'],
      blackPlans: ['Answer b5 with ...a6 or a timely ...c5', 'Kingside majority play with ...Ne4 and ...f5', 'The ...Re8, ...Nf8, ...Ne6 defensive regrouping'],
      breaks: [
        { move: 'b5', side: 'white', note: 'The minority attack.' },
        { move: 'f5', side: 'black', note: 'The kingside counter using the majority.' },
        { move: 'c5', side: 'black', note: 'Freeing break, at the cost of an isolani.' },
        { move: 'e4', side: 'white', note: 'The central alternative, changing the character completely.' },
      ],
      modelGames: ['Botvinnik – Keres, Moscow 1952'],
    },
  },
  { eco: 'D20', name: 'Queen’s Gambit Accepted', moves: line('d4 d5 c4 dxc4'), character: 'balanced', forSide: 'black' },
  {
    eco: 'D10',
    name: 'Slav Defence',
    moves: line('d4 d5 c4 c6'),
    character: 'positional',
    forSide: 'black',
    minRating: 1300,
    theory: {
      idea: 'Black supports d5 with the c-pawn, keeping the light-squared bishop’s diagonal open — the Slav’s advantage over the QGD. In return the ...c5 break costs an extra tempo. Rock solid, and the backbone of many elite repertoires.',
      structures: ['semi-slav-triangle'],
      whitePlans: ['Build the centre and aim for e4', 'Meet ...dxc4 and ...b5 with a4, opening the queenside', 'Exchange on d5 for a symmetrical, safe game'],
      blackPlans: ['Develop the bishop to f5 or g4 before playing ...e6', 'Grab and hold c4 with ...dxc4 and ...b5 when it can be supported', 'Free the game with ...c5 or ...e5'],
      breaks: [
        { move: 'c5', side: 'black', note: 'The main break; costs a tempo because the pawn already moved once.' },
        { move: 'e5', side: 'black', note: 'The other release, usually in Semi-Slav structures.' },
        { move: 'e4', side: 'white', note: 'The critical central advance the whole Meran fight revolves around.' },
        { move: 'a4', side: 'white', note: 'Undermines a black pawn on b5 before it gets supported by ...a6 and ...c5.' },
      ],
    },
  },
  { eco: 'D43', name: 'Semi-Slav Defence', moves: line('d4 d5 c4 c6 Nf3 Nf6 Nc3 e6'), character: 'sharp', minRating: 1600 },
  { eco: 'D07', name: 'Chigorin Defence', moves: line('d4 d5 c4 Nc6'), character: 'sharp', forSide: 'black' },
  {
    eco: 'D02',
    name: 'London System',
    moves: line('d4 d5 Bf4'),
    character: 'system',
    minRating: 600,
    theory: {
      idea: 'A setup rather than an opening: Bf4, e3, Nf3, c3, Bd3, Nbd2 and 0-0 against almost anything Black plays. Nearly zero memorisation, a safe structure, and a real middlegame plan — the most efficient way for a developing player to get a playable position every single game.',
      structures: [],
      whitePlans: [
        'Complete the setup, then play for e4 or the Ne5/Qf3/g4 kingside attack.',
        'Play c4 at a moment when the London bishop is already outside the chain.',
        'Use the standard sacrifice on h7 or the Ne5 build-up when Black castles kingside.',
      ],
      blackPlans: [
        'Play ...c5 and ...Qb6 hitting b2 and d4 — the main critical response.',
        'Trade the good bishop with ...Nh5 or ...Bd6.',
        'Take space with ...Bf5 before playing ...e6, so the bishop is not shut in.',
      ],
      breaks: [
        { move: 'e4', side: 'white', note: 'The freeing central break after the setup is complete.' },
        { move: 'c4', side: 'white', note: 'The more ambitious break, hitting d5.' },
        { move: 'c5', side: 'black', note: 'The standard counter, hitting d4 and opening the queenside.' },
        { move: 'e5', side: 'black', note: 'Challenges the London bishop directly.' },
      ],
    },
  },
  { eco: 'A45', name: 'Trompowsky Attack', moves: line('d4 Nf6 Bg5'), character: 'system' },

  // ------------------------------------------------------ Indian Defences ---
  {
    eco: 'E60',
    name: 'King’s Indian Defence',
    moves: line('d4 Nf6 c4 g6 Nc3 Bg7'),
    character: 'sharp',
    forSide: 'black',
    minRating: 1500,
    aliases: ['KID'],
    theory: {
      idea: 'Black concedes the whole centre, fianchettoes and then attacks it with ...e5 or ...c5. In the main lines the centre locks and the game becomes a pure race: White on the queenside, Black at the white king. Enormously ambitious and correspondingly risky — the KID does not produce quiet draws.',
      structures: ['kid-locked', 'benoni'],
      whitePlans: [
        'Close with d5 and attack on the queenside with c5 and the c-file.',
        'Slow Black’s kingside storm with Ne1-d3, f3 and g4.',
        'Trade dark-squared bishops to remove Black’s attacker.',
      ],
      blackPlans: [
        'The classic march: ...Ne8/...Nd7, ...f5, ...f4, ...g5, ...Rf6-h6, ...g4.',
        'Keep the queenside closed; every trade there helps White.',
        'Play ...c5 instead for a Benoni structure when White plays a set-up without e4.',
      ],
      breaks: [
        { move: 'e5', side: 'black', note: 'The central strike that defines the main lines; usually met by d5 locking the centre.' },
        { move: 'f5', side: 'black', note: 'Opens the kingside attack. Everything before it is preparation.' },
        { move: 'c5', side: 'white', note: 'White’s mirror break on the other wing — the race begins here.' },
        { move: 'c5', side: 'black', note: 'The Benoni-style alternative when White has not built the big centre.' },
      ],
      keySquares: [
        { square: 'f4', note: 'Black’s pawn wants to land here, shutting out White’s defensive pieces.' },
        { square: 'c7', note: 'The invasion square at the end of White’s c-file play.' },
      ],
      modelGames: ['Kasparov – Kramnik, Linares 1997'],
    },
  },
  { eco: 'E97', name: 'King’s Indian Defence: Mar del Plata', moves: line('d4 Nf6 c4 g6 Nc3 Bg7 e4 d6 Nf3 O-O Be2 e5 O-O Nc6 d5 Ne7'), character: 'sharp', minRating: 1800 },
  {
    eco: 'E20',
    name: 'Nimzo-Indian Defence',
    moves: line('d4 Nf6 c4 e6 Nc3 Bb4'),
    character: 'positional',
    forSide: 'black',
    minRating: 1500,
    theory: {
      idea: 'Black pins the c3 knight to stop e4 and is usually happy to trade bishop for knight, giving White doubled c-pawns in return for the bishop pair. The whole opening is a long argument between static structure and dynamic piece activity — the best possible opening for learning that trade-off.',
      structures: ['iqp', 'hanging-pawns', 'carlsbad'],
      whitePlans: [
        'Accept the doubled pawns and use the bishop pair in an open position.',
        'Avoid them with Qc2, keeping a clean structure at the cost of time.',
        'Play e3, Bd3, Nf3, 0-0 and push for e4.',
      ],
      blackPlans: [
        'Trade on c3 and blockade the doubled pawns with ...c5, ...b6, ...Ba6 and ...Na5.',
        'Fix c4 as a target and press it with pieces.',
        'Play ...d5 and ...c5 for a classical central fight instead.',
      ],
      breaks: [
        { move: 'c5', side: 'black', note: 'Hits d4 and fixes White’s doubled c-pawns as a target.' },
        { move: 'd5', side: 'black', note: 'The classical central approach, often producing hanging pawns or an IQP.' },
        { move: 'e4', side: 'white', note: 'The break the pin exists to prevent — achieving it usually means White is better.' },
        { move: 'f3', side: 'white', note: 'Preparation for e4 in the Sämisch and related lines.' },
      ],
      keySquares: [
        { square: 'e4', note: 'Both sides fight for this square from move three onward.' },
        { square: 'c4', note: 'Becomes a chronic weakness once White’s pawns are doubled.' },
      ],
      modelGames: ['Botvinnik – Capablanca, AVRO 1938'],
    },
  },
  { eco: 'E12', name: 'Queen’s Indian Defence', moves: line('d4 Nf6 c4 e6 Nf3 b6'), character: 'positional', forSide: 'black' },
  {
    eco: 'D80',
    name: 'Grünfeld Defence',
    moves: line('d4 Nf6 c4 g6 Nc3 d5'),
    character: 'sharp',
    forSide: 'black',
    minRating: 1700,
    theory: {
      idea: 'Black invites White to build a huge pawn centre and then attacks it from the flanks with ...c5, ...Bg7 and ...Nc6. It is hypermodernism in its purest form: the centre is a target, not an asset. Sharp, theoretical, and unforgiving of a single slow move.',
      structures: [],
      whitePlans: [
        'Build and hold the centre with e4, Bc4, Ne2, 0-0 and Be3.',
        'Push d5 to gain space and shut out the g7 bishop.',
        'Attack on the kingside while Black chips at the centre.',
      ],
      blackPlans: [
        'Hit d4 with ...c5, ...Bg7, ...Qa5 and ...Rd8.',
        'Trade off White’s centre and reach an endgame with a queenside majority.',
        'Use the long diagonal — the g7 bishop is the entire opening.',
      ],
      breaks: [
        { move: 'c5', side: 'black', note: 'The main break against White’s big centre; usually played immediately.' },
        { move: 'e5', side: 'black', note: 'The alternative undermining move in some structures.' },
        { move: 'd5', side: 'white', note: 'Gains space and blunts the g7 bishop.' },
      ],
      modelGames: ['Kasparov – Karpov, World Championship 1990'],
    },
  },
  { eco: 'A56', name: 'Modern Benoni', moves: line('d4 Nf6 c4 c5 d5 e6'), character: 'sharp', forSide: 'black', minRating: 1600 },
  { eco: 'A57', name: 'Benko Gambit', moves: line('d4 Nf6 c4 c5 d5 b5'), character: 'gambit', forSide: 'black' },
  {
    eco: 'E00',
    name: 'Catalan Opening',
    moves: line('d4 Nf6 c4 e6 g3'),
    character: 'positional',
    minRating: 1600,
    theory: {
      idea: 'White combines the Queen’s Gambit with a kingside fianchetto. The g2 bishop pressures d5 and the long diagonal forever, and Black’s main problem is untangling the queenside without leaving the c4 pawn permanently in White’s hands. A grinding, low-risk, high-pressure opening.',
      structures: ['semi-slav-triangle'],
      whitePlans: [
        'Recover the c4 pawn with Qa4, Qc2 or Ne5 and keep the bishop pressure.',
        'Play e4 for a full central bind.',
        'Squeeze on the queenside and in the endgame; the g2 bishop never gets worse.',
      ],
      blackPlans: [
        'Hold c4 with ...dxc4 and ...b5, accepting a sharp fight.',
        'Give it back for the ...c5 break and free play.',
        'Neutralise the long diagonal with ...Bb7 and ...c6, or trade bishops with ...Ba6 and ...Bb4+.',
      ],
      breaks: [
        { move: 'c5', side: 'black', note: 'The main freeing break; the Catalan is comfortable for Black once it lands.' },
        { move: 'e5', side: 'black', note: 'The alternative release, usually after ...Nbd7 and ...Re8.' },
        { move: 'e4', side: 'white', note: 'The central advance that turns pressure into a bind.' },
        { move: 'a4', side: 'white', note: 'Undermines ...b5 in the Open Catalan.' },
      ],
    },
  },

  // ------------------------------------------------------- Dutch and flank ---
  {
    eco: 'A80',
    name: 'Dutch Defence',
    moves: line('d4 f5'),
    character: 'sharp',
    forSide: 'black',
    theory: {
      idea: 'Black grabs e4 and plays for a kingside attack from move one, at the cost of weakening the king and the a2-g8 diagonal. It comes in three flavours — Stonewall, Leningrad and Classical — that produce genuinely different games from the same first move.',
      structures: ['stonewall'],
      whitePlans: ['Fianchetto with g3 and Bg2, hitting the weakened light squares', 'Occupy e5', 'Open the position quickly with e4 or the Staunton Gambit'],
      blackPlans: ['Stonewall: ...d5, ...e6, ...c6 with a permanent grip on e4', 'Leningrad: ...g6 and ...Bg7 with ...e5 to follow', 'Attack with ...Qe8-h5, ...Ne4 and ...Rf6-h6'],
      breaks: [
        { move: 'e5', side: 'black', note: 'The Leningrad break, freeing the position and opening the g7 bishop.' },
        { move: 'g5', side: 'black', note: 'The Stonewall attacking break.' },
        { move: 'e4', side: 'white', note: 'Challenges Black’s grip on the key square directly.' },
      ],
    },
  },
  { eco: 'A90', name: 'Dutch Defence: Stonewall Variation', moves: line('d4 f5 c4 Nf6 g3 e6 Bg2 d5'), character: 'positional' },
  {
    eco: 'A10',
    name: 'English Opening',
    moves: line('c4'),
    character: 'positional',
    minRating: 1400,
    theory: {
      idea: 'A flank opening that fights for d5 from the side. It transposes into an enormous number of other openings — reversed Sicilians, Catalans, Queen’s Gambits — so it rewards understanding of structures far more than memorised lines.',
      structures: ['maroczy', 'hedgehog'],
      whitePlans: ['Fianchetto with g3 and Bg2 and press on the long diagonal', 'Play the reversed Sicilian with an extra tempo after 1...e5', 'Build a Maróczy-style bind with c4 and e4'],
      blackPlans: ['Take the centre with ...e5 or ...d5', 'Play a Hedgehog setup with ...c5, ...e6, ...b6 and ...d6', 'Transpose to a Queen’s Gambit or a King’s Indian on your own terms'],
      breaks: [
        { move: 'd4', side: 'white', note: 'The central break that turns the flank opening into a full centre.' },
        { move: 'd5', side: 'black', note: 'The main equalising break against the English.' },
        { move: 'b4', side: 'white', note: 'Queenside expansion, often supported by a3 and Rb1.' },
      ],
    },
  },
  { eco: 'A04', name: 'Réti Opening', moves: line('Nf3'), character: 'positional' },
  { eco: 'A01', name: 'Nimzo-Larsen Attack', moves: line('b3'), character: 'system' },
  { eco: 'A02', name: 'Bird’s Opening', moves: line('f4'), character: 'system' },

  // ------------------------------------------------- deeper main lines ---
  // Named continuations of the entries above, carrying the tree far enough
  // that a training session is a real line rather than two moves. They hold no
  // theory of their own on purpose: each inherits its parent's ideas, which is
  // what a player reaching this position actually needs.
  { eco: 'B22', name: 'Sicilian Defence: Alapin, Barmen Variation', moves: line('e4 c5 c3 d5 exd5 Qxd5 d4 Nf6 Nf3') },
  { eco: 'B22', name: 'Sicilian Defence: Alapin, 2...Nf6', moves: line('e4 c5 c3 Nf6 e5 Nd5 d4 cxd4 Nf3') },
  { eco: 'B25', name: 'Sicilian Defence: Closed, Traditional', moves: line('e4 c5 Nc3 Nc6 g3 g6 Bg2 Bg7 d3') },
  { eco: 'B31', name: 'Sicilian Defence: Rossolimo, Fianchetto', moves: line('e4 c5 Nf3 Nc6 Bb5 g6 O-O Bg7 c3') },
  // 4...Nf6 needs no disambiguation: the d7 knight is pinned by the bishop.
  { eco: 'B52', name: 'Sicilian Defence: Moscow, Main Line', moves: line('e4 c5 Nf3 d6 Bb5+ Nd7 O-O Nf6 Re1') },
  { eco: 'B90', name: 'Sicilian Defence: Najdorf, English Attack', moves: line('e4 c5 Nf3 d6 d4 cxd4 Nxd4 Nf6 Nc3 a6 Be3 e5 Nb3 Be6 f3'), character: 'sharp' },
  { eco: 'B76', name: 'Sicilian Defence: Dragon, Yugoslav Attack', moves: line('e4 c5 Nf3 d6 d4 cxd4 Nxd4 Nf6 Nc3 g6 Be3 Bg7 f3 O-O Qd2 Nc6'), character: 'sharp' },
  { eco: 'B81', name: 'Sicilian Defence: Scheveningen, Keres Attack', moves: line('e4 c5 Nf3 e6 d4 cxd4 Nxd4 Nf6 Nc3 d6 g4'), character: 'sharp' },
  { eco: 'B33', name: 'Sicilian Defence: Sveshnikov, Main Line', moves: line('e4 c5 Nf3 Nc6 d4 cxd4 Nxd4 Nf6 Nc3 e5 Ndb5 d6 Bg5 a6 Na3 b5') },
  { eco: 'B42', name: 'Sicilian Defence: Kan, Modern Variation', moves: line('e4 c5 Nf3 e6 d4 cxd4 Nxd4 a6 Bd3 Nf6 O-O') },
  { eco: 'B47', name: 'Sicilian Defence: Taimanov, Main Line', moves: line('e4 c5 Nf3 e6 d4 cxd4 Nxd4 Nc6 Nc3 Qc7 Be3 a6') },
  { eco: 'B01', name: 'Scandinavian Defence: Main Line', moves: line('e4 d5 exd5 Qxd5 Nc3 Qa5 d4 Nf6 Nf3') },
  { eco: 'B04', name: 'Alekhine Defence: Modern Variation', moves: line('e4 Nf6 e5 Nd5 d4 d6 Nf3') },
  { eco: 'B06', name: 'Modern Defence: Standard Line', moves: line('e4 g6 d4 Bg7 Nc3 d6 f4') },
  { eco: 'B08', name: 'Pirc Defence: Classical Variation', moves: line('e4 d6 d4 Nf6 Nc3 g6 Nf3 Bg7 Be2') },
  { eco: 'C41', name: 'Philidor Defence: Main Line', moves: line('e4 e5 Nf3 d6 d4 exd4 Nxd4 Nf6 Nc3') },
  { eco: 'C29', name: 'Vienna Gambit', moves: line('e4 e5 Nc3 Nf6 f4 d5 fxe5 Nxe4'), character: 'gambit' },
  { eco: 'C39', name: 'King’s Gambit Accepted: Kieseritzky', moves: line('e4 e5 f4 exf4 Nf3 g5 h4 g4 Ne5'), character: 'gambit' },
  { eco: 'C42', name: 'Petrov Defence: Classical Attack', moves: line('e4 e5 Nf3 Nf6 Nxe5 d6 Nf3 Nxe4 d4 d5') },
  { eco: 'C45', name: 'Scotch Game: Main Line', moves: line('e4 e5 Nf3 Nc6 d4 exd4 Nxd4 Nf6 Nxc6 bxc6 e5') },
  { eco: 'C67', name: 'Ruy Lopez: Berlin Wall', moves: line('e4 e5 Nf3 Nc6 Bb5 Nf6 O-O Nxe4 d4 Nd6 Bxc6 dxc6 dxe5 Nf5 Qxd8+ Kxd8'), character: 'positional' },
  { eco: 'C68', name: 'Ruy Lopez: Exchange, Main Line', moves: line('e4 e5 Nf3 Nc6 Bb5 a6 Bxc6 dxc6 O-O') },
  { eco: 'C53', name: 'Italian Game: Giuoco Pianissimo', moves: line('e4 e5 Nf3 Nc6 Bc4 Bc5 c3 Nf6 d3') },
  { eco: 'C58', name: 'Italian Game: Two Knights, Polerio Defence', moves: line('e4 e5 Nf3 Nc6 Bc4 Nf6 Ng5 d5 exd5 Na5'), character: 'sharp' },
  { eco: 'C51', name: 'Evans Gambit Accepted', moves: line('e4 e5 Nf3 Nc6 Bc4 Bc5 b4 Bxb4 c3 Ba5'), character: 'gambit' },
  { eco: 'C01', name: 'French Defence: Exchange, Main Line', moves: line('e4 e6 d4 d5 exd5 exd5 Nf3 Nf6 Bd3') },
  { eco: 'C09', name: 'French Defence: Tarrasch, Open Variation', moves: line('e4 e6 d4 d5 Nd2 c5 exd5 exd5 Ngf3') },
  { eco: 'C11', name: 'French Defence: Steinitz Variation', moves: line('e4 e6 d4 d5 Nc3 Nf6 e5 Nfd7 f4') },
  { eco: 'C19', name: 'French Defence: Winawer, Main Line', moves: line('e4 e6 d4 d5 Nc3 Bb4 e5 c5 a3 Bxc3+ bxc3 Ne7') },
  { eco: 'B12', name: 'Caro-Kann Defence: Advance, Short Variation', moves: line('e4 c6 d4 d5 e5 Bf5 Nf3 e6 Be2') },
  { eco: 'B19', name: 'Caro-Kann Defence: Classical, Main Line', moves: line('e4 c6 d4 d5 Nc3 dxe4 Nxe4 Bf5 Ng3 Bg6 h4 h6 Nf3') },
  { eco: 'D27', name: 'Queen’s Gambit Accepted: Classical', moves: line('d4 d5 c4 dxc4 Nf3 Nf6 e3 e6 Bxc4 c5') },
  { eco: 'D07', name: 'Chigorin Defence: Main Line', moves: line('d4 d5 c4 Nc6 Nf3 Bg4 cxd5 Bxf3 gxf3 Qxd5') },
  { eco: 'D17', name: 'Slav Defence: Czech Variation', moves: line('d4 d5 c4 c6 Nf3 Nf6 Nc3 dxc4 a4 Bf5') },
  { eco: 'D47', name: 'Semi-Slav Defence: Meran Variation', moves: line('d4 d5 c4 c6 Nf3 Nf6 Nc3 e6 e3 Nbd7 Bd3 dxc4 Bxc4 b5'), character: 'sharp' },
  { eco: 'D60', name: 'Queen’s Gambit Declined: Orthodox Defence', moves: line('d4 d5 c4 e6 Nc3 Nf6 Bg5 Be7 e3 O-O') },
  { eco: 'D02', name: 'London System: Main Line', moves: line('d4 d5 Bf4 Nf6 e3 e6 Nf3 c5 c3 Nc6 Nbd2 Bd6') },
  { eco: 'A45', name: 'Trompowsky Attack: Main Line', moves: line('d4 Nf6 Bg5 Ne4 Bf4 d5 e3') },
  { eco: 'E40', name: 'Nimzo-Indian Defence: Rubinstein Variation', moves: line('d4 Nf6 c4 e6 Nc3 Bb4 e3') },
  { eco: 'E15', name: 'Queen’s Indian Defence: Fianchetto Variation', moves: line('d4 Nf6 c4 e6 Nf3 b6 g3 Ba6') },
  { eco: 'E80', name: 'King’s Indian Defence: Sämisch Variation', moves: line('d4 Nf6 c4 g6 Nc3 Bg7 e4 d6 f3'), character: 'sharp' },
  { eco: 'D85', name: 'Grünfeld Defence: Exchange Variation', moves: line('d4 Nf6 c4 g6 Nc3 d5 cxd5 Nxd5 e4 Nxc3 bxc3 Bg7'), character: 'sharp' },
  { eco: 'A70', name: 'Modern Benoni: Classical Variation', moves: line('d4 Nf6 c4 c5 d5 e6 Nc3 exd5 cxd5 d6 e4 g6 Nf3 Bg7') },
  { eco: 'A58', name: 'Benko Gambit Accepted', moves: line('d4 Nf6 c4 c5 d5 b5 cxb5 a6 bxa6 Bxa6'), character: 'gambit' },
  { eco: 'E04', name: 'Catalan Opening: Open Defence', moves: line('d4 Nf6 c4 e6 g3 d5 Bg2 dxc4 Nf3') },
  { eco: 'A87', name: 'Dutch Defence: Leningrad Variation', moves: line('d4 f5 c4 Nf6 g3 g6 Bg2 Bg7 Nf3 O-O') },
  { eco: 'A90', name: 'Dutch Defence: Stonewall, Modern Line', moves: line('d4 f5 c4 Nf6 g3 e6 Bg2 d5 Nf3 c6 O-O Bd6') },
  { eco: 'A20', name: 'English Opening: Reversed Sicilian', moves: line('c4 e5 Nc3 Nf6 Nf3 Nc6 g3 d5 cxd5 Nxd5') },
  { eco: 'A30', name: 'English Opening: Symmetrical, Hedgehog', moves: line('c4 c5 Nf3 Nf6 g3 b6 Bg2 Bb7 O-O e6') },
];
