/** Generate an offline position + legal-move index; never replay the corpus in the browser. */
import { readFile, writeFile } from 'node:fs/promises';
import { Chess, parseMoveText } from '@coh/chess-core';
import { OPENINGS } from '../src/book.js';
import { theoryPositionKey } from '../src/theory-position.js';

const positions = new Map<string, Set<string>>();
const names = new Map<string, { eco: string; name: string }>();
const prefixes = new Map<string, { fen: string; uci: string }>();
const unsafePositions = new Map<string, boolean>();
let excludedTrapEdges = 0;
let deepestPly = 0;
let masterLines = 0;
let deepMasterLines = 0;

function replay(moves: readonly string[]): string {
  let fen = new Chess().fen();
  let prefix = '';
  // Validate the entire line before adding any of its edges.
  const edges: { before: string; after: string; uci: string }[] = [];
  for (const san of moves) {
    prefix += ` ${san}`;
    let step = prefixes.get(prefix);
    if (!step) {
      const board = new Chess(fen);
      const move = board.move(san);
      if (!move) throw new Error(`Illegal theory move: ${prefix}`);
      step = { fen: board.fen(), uci: move.uci };
      prefixes.set(prefix, step);
    }
    edges.push({ before: theoryPositionKey(fen), after: step.fen, uci: step.uci });
    fen = step.fen;
  }
  for (const { before, after, uci } of edges) {
    const afterKey = theoryPositionKey(after);
    let unsafe = unsafePositions.get(afterKey);
    if (unsafe === undefined) {
      const board = new Chess(after);
      const replies = board.legalMoves();
      // Naming datasets also contain instructional traps. A move allowing
      // mate in one (or ending the game) is not preparation credit. Stop that
      // line here; don't promote its subsequent mating moves into theory.
      unsafe = replies.length === 0 || replies.some((move) => move.san.endsWith('#'));
      unsafePositions.set(afterKey, unsafe);
    }
    if (unsafe) { excludedTrapEdges++; break; }
    let moves = positions.get(before);
    if (!moves) positions.set(before, moves = new Set());
    moves.add(uci);
  }
  deepestPly = Math.max(deepestPly, moves.length);
  return theoryPositionKey(fen);
}

for (const opening of OPENINGS) {
  const key = replay(opening.moves);
  // Curated names are first and win on a position collision.
  if (!names.has(key)) names.set(key, { eco: opening.eco, name: opening.name });
}
const masters = await readFile(new URL('../data/masters.tsv', import.meta.url), 'utf8');
for (const row of masters.trim().split('\n').slice(1)) {
  const [count, pgn] = row.split('\t');
  if (!pgn || Number(count) < 8) throw new Error(`Invalid master row: ${row}`);
  const moves = parseMoveText(pgn);
  replay(moves);
  masterLines++;
  if (moves.length >= 42) deepMasterLines++;
}

const keys = [...new Set([...positions.keys(), ...names.keys()])].sort();
const text = keys.map((key) => {
  const opening = names.get(key);
  return [key, [...(positions.get(key) ?? [])].sort().join(' '), opening?.eco ?? '', opening?.name ?? ''].join('\t');
}).join('\n');
const stats = { namedLines: OPENINGS.length, masterLines, deepMasterLines, positions: positions.size, moves: [...positions.values()].reduce((n, moves) => n + moves.size, 0), deepestPly, excludedTrapEdges };
const output = `/** AUTO-GENERATED by npm run ingest:theory. Sources and licenses: ../data/README.md. */\nexport const THEORY_STATS = ${JSON.stringify(stats)} as const;\n/** position, legal UCI continuations, ECO, name (tab-separated). */\nexport const THEORY_TSV = ${JSON.stringify(text)};\n`;
await writeFile(new URL('../src/theory.generated.ts', import.meta.url), output);
console.log(stats);
